#cloud-config

users:
  - default
  - name: james
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPLeKBVlf2D3JuJvamlDJGBoglJwhzx3y/LlKaBgZduN